export enum PDF_CREATE_PAGE_ITEM {
  TEXT = "text",
  IMAGE = "image",
  RECTANGLE = "rectangle",
  SVG = "svg",
}

export enum PDF_ORIENTATION {
  PORTRAIT = "portrait",
  LANDSCAPE = "landscape",
}

export enum PDF_MEDIA_TYPE {
  SCREEN = "screen",
  PRINT = "print",
}

export enum PDF_PAGE_SIZE {
  A0 = "A0",
  A1 = "A1",
  A2 = "A2",
  A3 = "A3",
  A4 = "A4",
  A5 = "A5",
  A6 = "A6",
  LETTER = "Letter",
  LEGAL = "Legal",
  TABLOID = "Tabloid",
  LEDGER = "Ledger",
}

export enum IMAGE_FORMAT {
  JPG = "jpg",
  PNG = "png",
  TIFF = "tiff",
  BMP = "bmp",
}

export enum PDF_TO_DOCUMENT_OUTPUT {
  DOC = "doc",
  DOCX = "docx",
}

export enum PDF_PROTECT_PERMISSIONS {
  PRINTING = "Printing",
  DEGRADED_PRINTIN = "DegradedPrintin",
  MODIFY_CONTENTS = "ModifyContents",
  ASSEMBLY = "Assembly",
  COPY_CONTENTS = "CopyContents",
  SCREEN_READERS = "ScreenReaders",
  MODIFY_ANNOTATIONS = "ModifyAnnotations",
  FILL_IN = "FillIn",
  ALL_FEATURES = "AllFeatures",
}

export enum BARCODES_TYPES {
  AZTECCODE = "azteccode",
  AUSPOST = "auspost",
  AZTECCODECOMPACT = "azteccodecompact",
  AZTECRUNE = "aztecrune",
  BC412 = "bc412",
  CHANNELCODE = "channelcode",
  CODABLOCKF = "codablockf",
  CODE11 = "code11",
  CODE128 = "code128",
  CODE16K = "code16k",
  CODE2OF5 = "code2of5",
  CODE32 = "code32",
  CODE39 = "code39",
  CODE39EXT = "code39ext",
  CODE49 = "code49",
  CODE93 = "code93",
  CODE93EXT = "code93ext",
  CODEONE = "codeone",
  COOP2OF5 = "coop2of5",
  DAFT = "daft",
  DATABAREXPANDED = "databarexpanded",
  DATABAREXPANDEDCOMPOSITE = "databarexpandedcomposite",
  DATABAREXPANDEDSTACKED = "databarexpandedstacked",
  DATABAREXPANDEDSTACKEDCOMPOSITE = "databarexpandedstackedcomposite",
  DATABARLIMITED = "databarlimited",
  DATABARLIMITEDCOMPOSITE = "databarlimitedcomposite",
  DATABAROMNI = "databaromni",
  DATABAROMNICOMPOSITE = "databaromnicomposite",
  DATABARSTACKED = "databarstacked",
  DATABARSTACKEDCOMPOSITE = "databarstackedcomposite",
  DATABARSTACKEDOMNI = "databarstackedomni",
  DATABARSTACKEDOMNICOMPOSITE = "databarstackedomnicomposite",
  DATABARTRUNCATED = "databartruncated",
  DATABARTRUNCATEDCOMPOSITE = "databartruncatedcomposite",
  DATALOGIC2OF5 = "datalogic2of5",
  DATAMATRIX = "datamatrix",
  DATAMATRIXRECTANGULAR = "datamatrixrectangular",
  DATAMATRIXRECTANGULAREXTENSION = "datamatrixrectangularextension",
  DOTCODE = "dotcode",
  EAN13 = "ean13",
  EAN13COMPOSITE = "ean13composite",
  EAN14 = "ean14",
  EAN2 = "ean2",
  EAN5 = "ean5",
  EAN8 = "ean8",
  EAN8COMPOSITE = "ean8composite",
  FLATTERMARKEN = "flattermarken",
  "GS1-128" = "gs1-128",
  "GS1-128COMPOSITE" = "gs1-128composite",
  "GS1-CC" = "gs1-cc",
  GS1DATAMATRIX = "gs1datamatrix",
  GS1DATAMATRIXRECTANGULAR = "gs1datamatrixrectangular",
  GS1NORTHAMERICANCOUPON = "gs1northamericancoupon",
  GS1QRCODE = "gs1qrcode",
  HANXIN = "hanxin",
  HIBCAZTECCODE = "hibcazteccode",
  HIBCCODABLOCKF = "hibccodablockf",
  HIBCCODE128 = "hibccode128",
  HIBCCODE39 = "hibccode39",
  HIBCDATAMATRIX = "hibcdatamatrix",
  HIBCDATAMATRIXRECTANGULAR = "hibcdatamatrixrectangular",
  HIBCMICROPDF417 = "hibcmicropdf417",
  HIBCPDF417 = "hibcpdf417",
  HIBCQRCODE = "hibcqrcode",
  IATA2OF5 = "iata2of5",
  IDENTCODE = "identcode",
  INDUSTRIAL2OF5 = "industrial2of5",
  INTERLEAVED2OF5 = "interleaved2of5",
  ISBN = "isbn",
  ISMN = "ismn",
  ISSN = "issn",
  ITF14 = "itf14",
  JAPANPOST = "japanpost",
  KIX = "kix",
  LEITCODE = "leitcode",
  MAILMARK = "mailmark",
  MATRIX2OF5 = "matrix2of5",
  MAXICODE = "maxicode",
  MICROPDF417 = "micropdf417",
  MICROQRCODE = "microqrcode",
  MSI = "msi",
  ONECODE = "onecode",
  PDF417 = "pdf417",
  PDF417COMPACT = "pdf417compact",
  PHARMACODE = "pharmacode",
  PHARMACODE2 = "pharmacode2",
  PLANET = "planet",
  PLESSEY = "plessey",
  POSICODE = "posicode",
  POSTNET = "postnet",
  PZN = "pzn",
  QRCODE = "qrcode",
  RATIONALIZEDCODABAR = "rationalizedCodabar",
  RAW = "raw",
  ROYALMAIL = "royalmail",
  SSCC18 = "sscc18",
  SYMBOL = "symbol",
  TELEPEN = "telepen",
  TELEPENNUMERIC = "telepennumeric",
  ULTRACODE = "ultracode",
  UPCA = "upca",
  UPCACOMPOSITE = "upcacomposite",
  UPCE = "upce",
  UPCECOMPOSITE = "upcecomposite",
}

export enum TEXT_ALIGMENT {
  LEFT = "left",
  RIGHT = "right",
  CENTER = "center",
}

export enum BARCODE_ROTATION {
  N = "N",
  L = "L",
  R = "R",
  I = "I",
}
